name: Build and Release

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.2'

      - name: Install Dependencies
        run: flutter pub get

      # - name: Run Tests and Generate Coverage Report
      #   run: flutter test --coverage

      - name: Generate SonarQube Properties
        run: |
          echo "sonar.projectKey=proting-newcity_NewCity-Mobile-FE" > sonar-project.properties
          echo "sonar.organization=proting-newcity" >> sonar-project.properties
          echo "sonar.host.url=https://sonarcloud.io" >> sonar-project.properties
          echo "sonar.sources=lib" >> sonar-project.properties
          echo "sonar.tests=test" >> sonar-project.properties
          echo "sonar.exclusions=**/*.g.dart" >> sonar-project.properties
          echo "sonar.coverage.exclusions=**/*.g.dart" >> sonar-project.properties
          echo "sonar.flutter.reportPaths=coverage/lcov.info" >> sonar-project.properties
          echo "sonar.java.binaries=build" >> sonar-project.properties

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed for PR decoration

  build_and_release:
    name: Build and Release APK
    needs: sonarqube # This job will start only after sonarqube job is successful
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.2'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Create Release and Upload APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          token: ${{ secrets.GITHUB_TOKEN }}